super_django_prj/recipe_project/recipe_catalog/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, reverse_lazy
from django.views.generic import CreateView

from .models import User
from .views import about, index, detail, ingredient, ingredient_edit, ingredient_delete, recipe_create, \
    recipe_edit, recipe_delete, my_recipes, ingredients_list

from django.conf import settings
from django.conf.urls.static import static

app_name = 'recipe_catalog'

urlpatterns = [
                  path('', index, name='home'),
                  path('recipe/<int:pk>/', detail, name='detail'),
                  path('about/', about, name='about'),
                  path('ingredient/', ingredient, name='ingredient'),
                  path('ingredient/<int:pk>/edit/', ingredient_edit, name='ingredient_edit'),
                  path('ingredient/<int:pk>/delete/', ingredient_delete, name='ingredient_delete'),

                  path('recipe/', recipe_create, name='recipe_create'),
                  path('recipe/<int:pk>/edit/', recipe_edit, name='recipe_edit'),
                  path('recipe/<int:pk>/delete/', recipe_delete, name='recipe_delete'),

                  path('my_recipes/', my_recipes, name='my_recipes'),
                  path('ingredients_list/', ingredients_list, name='ingredients_list'),

                  path('auth/login/', views.LoginView.as_view(template_name='login.html'), name='login'),
                  path('auth/register/', CreateView.as_view(
                      template_name='register.html',
                      model=User,
                      form_class=UserCreationForm,
                      success_url=reverse_lazy('recipe_catalog:home')
                  ), name='register'),
                  path('auth/logout/', views.LogoutView.as_view(), name='logout'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

super_django_prj/recipe_project/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe_catalog.urls'))
]

super_django_prj/recipe_project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:"Мой сайт" }}</title>
    <link rel="icon" href="fav.ico" type="image">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            font-family: sans-serif;
            background-color: #f8f9fa;
        }

        .bg-light-pink {
            background-color: #f8f0e3;
        }

        .text-dark-pink {
            color: #f18e85;
        }

        .dropdown-menu {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .nav-item.show .dropdown-menu {
            display: block;
        }

        .dropdown-menu a {
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            color: #333;
        }

        .dropdown-menu a:hover {
            background-color: #f18e85;
            color: #fff;
        }
    </style>


</head>
<body>
{% include "menu.html" %}

<main class="container my-5">
    {% block content %}
    {% endblock %}
</main>

{% include "footer.html" %}
</body>
</html>

super_django_prj/recipe_project/templates/footer.html
<footer class="bg-light-pink text-center text-dark-pink fw-bold py-3 rounded-top mt-4">
    <p>&copy; 2024. Все права защищены.</p>
</footer>

super_django_prj/recipe_project/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{% url 'recipe_catalog:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

super_django_prj/recipe_project/templates/menu.html
<header class="bg-light-pink shadow-sm rounded-bottom py-3 mb-4">
    <nav class="container d-flex justify-content-center">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:home' %}">Главная страница</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:about' %}">О сайте</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:my_recipes' %}">Мои рецепты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:ingredients_list' %}">Ингредиенты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:recipe_create' %}">Добавить
                    рецепт</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark-pink fw-bold" href="{% url 'recipe_catalog:ingredient' %}">Добавить
                    ингредиент</a>
            </li>
            <li class="nav-item dropdown" id="user-dropdown">
                <a class="nav-link text-dark-pink fw-bold dropdown-toggle" href="#" id="dropdownMenuButton"
                   role="button"
                   aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="{% url 'recipe_catalog:logout' %}">Выйти</a></li>
                </ul>
            </li>
            {% else %}
            <li class="nav-item dropdown" id="user-dropdown">
                <a class="nav-link text-dark-pink fw-bold dropdown-toggle" href="#" id="dropdownMenuButton"
                   role="button"
                   aria-expanded="false">
                    Войти
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="{% url 'recipe_catalog:login' %}">Вход</a></li>
                    <li><a class="dropdown-item" href="{% url 'recipe_catalog:register' %}">Регистрация</a></li>
                </ul>
            </li>
            {% endif %}
            <script>
                document.querySelectorAll('.nav-item.dropdown').forEach(function (item) {
                    item.addEventListener('click', function (e) {
                        this.classList.toggle('show');
                    });
                });

                document.addEventListener('click', function (e) {
                    if (!e.target.closest('.nav-item.dropdown')) {
                        document.querySelectorAll('.nav-item.dropdown').forEach(function (item) {
                            item.classList.remove('show');
                        });
                    }
                });
            </script>
        </ul>
    </nav>
</header>

super_django_prj/recipe_project/templates/register.html
{% extends "base.html" %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}